spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://AUTH
          predicates:
            - Path=/auth/login, /auth/signup
        - id: account-delete
          uri: lb://AUTH
          predicates:
            - Path=/account
            - Method=DELETE
          filters:
            - AuthenticationFilter
        - id: posts
          uri: lb://POSTS
          predicates:
            - Path=/posts/**
            - Method=GET,POST
          filters:
            - AuthenticationFilter
        - id: post-details-delete
          uri: lb://POST-DETAILS
          predicates:
            - Path=/posts/**
            - Method=DELETE
          filters:
            - AuthenticationFilter
        - id: post-details-get-by-user
          uri: lb://POST-DETAILS
          predicates:
            - Path=/user/posts
            - Method=GET
          filters:
            - AuthenticationFilter



server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka
