spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://AUTH
          predicates:
            - Path=/auth/login, /auth/signup

        - id: account-delete
          uri: lb://AUTH
          predicates:
            - Path=/account
            - Method=DELETE
          filters:
            - AuthenticationFilter

        - id: posts
          uri: lb://POSTS
          predicates:
            - Path=/posts
            - Method=POST
          filters:
            - AuthenticationFilter

        - id: posts
          uri: lb://POSTS
          predicates:
            - Path=/posts/{objectName}
            - Method=GET
          filters:
            - AuthenticationFilter

        - id: post-details-delete
          uri: lb://POST-DETAILS
          predicates:
            - Path=/posts, /user/posts
            - Method=DELETE, GET
          filters:
            - AuthenticationFilter

        - id: comments
          uri: lb://COMMENTS
          predicates:
            - Path=/comments
          filters:
            - AuthenticationFilter

        - id: comments-by-post
          uri: lb://COMMENTS
          predicates:
            - Path=/posts/{postId}/comments
          filters:
            - AuthenticationFilter




server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka
