spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://AUTH
          predicates:
            - Path=/auth/login, /auth/signup
        - id: account-delete
          uri: lb://AUTH
          predicates:
            - Path=/account
            - Method=DELETE
          filters:
            - AuthenticationFilter
        - id: user-details
          uri: lb://USER-DETAILS
          predicates:
            - Path=/a
            - Method=GET
          filters:
            - AuthenticationFilter
        - id: posts
          uri: lb://POSTS
          predicates:
            - Path=/posts/**
          filters:
            - AuthenticationFilter

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka
